/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package girdbaglayout;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Hoang Nam
 */
public class ListFram extends javax.swing.JPanel {

    /**
     * Creates new form List
     */
    public ListFram() {
        initComponents();
        loadIMG();
    }

     public void loadIMG(){
        File f = new File("D:/IMG_JavaIcon");
        File [] list = f.listFiles();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(20, 20, 20, 20);
        int x = 0; int y =0;
        for(int i =0; i<list.length; i++){
            Productinfor obj = new Productinfor();
            obj.setImage(new ImageIcon(list[i].getAbsolutePath()));
            obj.setpName(list[i].getName().substring(0, list[i].getName().length()-4));
            gbc.gridx = x;
            gbc.gridy = y;
            pnlProduct.add(obj, gbc);
            x++;
            if(x==4){
                x=0;
                y++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlProduct = new javax.swing.JPanel();

        pnlProduct.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(pnlProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlProduct;
    // End of variables declaration//GEN-END:variables
}
