package girdbaglayout;

import java.awt.GridBagConstraints;
import java.awt.Insets;


public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        loadProduct();
//        GridBagConstraints gbc = new GridBagConstraints();
//        gbc.insets = new Insets(20, 20, 20, 20);
//        
//        gbc.gridx = 0;
//        gbc.gridy = 0;
//        Productinfor p1 = new Productinfor();
//        pnlProduct.add(p1, gbc);
//        
//         Productinfor p2 = new Productinfor();
//        pnlProduct.add(p2);
//        
//        Productinfor p3 = new Productinfor();
//        pnlProduct.add(p3);
    }

    public void loadProduct() {
        Productinfor[] arr = {new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(), new Productinfor(),};
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(20, 20, 20, 20);
        int x = 0; int y = 0;
        for(int i=0; i<arr.length; i++){
            gbc.gridx = x;
            gbc.gridy = y;
            pnlProduct.add(arr[i], gbc);
            x++;
            if(x==3){
                x=0;
                y++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlProduct = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlProduct.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(pnlProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlProduct;
    // End of variables declaration//GEN-END:variables
}
